export type Project = {
  slug: string;
  name: string;
  location: string;
  category: string;
  area: string;
  year: string;
  image: string;
  gallery?: string[];
  blurb: string;
  segment: 'commercial' | 'residential';
  alt?: string;
};

export const staticProjects: Project[] = [
  {
    slug: 'gucci',
    name: 'Gucci',
    location: 'India',
    category: 'Luxury Retail',
    area: '3,500 sq ft',
    year: '2023',
    image: '/imgs/commercial/guccicoverimg.png',
    gallery: ['/imgs/commercial/guccicoverimg.png', '/imgs/commercial/gucci.png', '/imgs/commercial/gucci1.png'],
    blurb: "BrandKettle's first high-end luxury project. After the successful execution of Gucci's premium showroom, the owners personally appreciated the craftsmanship and attention to detail. Every detail — from custom finishes to ambient lighting — reflects the iconic elegance of the Gucci brand.",
    segment: 'commercial',
    alt: 'Retail Interior Contractors - Gucci Luxury Retail Store',
  },
  {
    slug: 'taksha-hyderabad',
    name: 'Taksha',
    location: 'Hyderabad',
    category: 'Commercial Spaces',
    area: '475 sq yd',
    year: '2023',
    image: '/imgs/commercial/taksha coverimg.png',
    gallery: ['/imgs/commercial/taksha coverimg.png', '/imgs/commercial/taksha.png', '/imgs/commercial/taksha1.png', '/imgs/commercial/taksha3.png'],
    blurb: 'A 475 sq. yd. premium builder floor by Studio AKAAI, blending comfort, functionality and exclusivity with a modern façade and luxury design. Crafted for refined lifestyles, it redefines contemporary urban living.',
    segment: 'commercial',
    alt: 'Commercial Interior Company in Indore - Taksha Hyderabad Builder Floor',
  },
  {
    slug: 'png',
    name: 'PNG Jewellers',
    location: 'Goregaon, Mumbai',
    category: 'Jewellery Showroom',
    area: '3,400 sq ft',
    year: '27 days',
    image: '/imgs/commercial/pnjcoverimg.png',
    gallery: ['/imgs/commercial/pnjcoverimg.png', '/imgs/commercial/png2.jpg', '/imgs/commercial/png3.jpg'],
    blurb: "BrandKettle transformed a 3,400 sq ft space in Goregaon into a luxurious retail destination in just 27 days. A turnkey project blending elegance and efficiency, bringing the brand's vision to life with precision and speed.",
    segment: 'commercial',
    alt: 'Jewellery Showroom Fit-Out - PNG Jewellers Goregaon',
  },
  {
    slug: 'giva',
    name: 'Giva',
    location: 'India',
    category: 'Jewellery Showroom',
    area: '1,200 sq ft',
    year: '2024',
    image: '/imgs/commercial/giaa.png',
    gallery: ['/imgs/commercial/giaa.png', '/imgs/commercial/jwellary.png', '/imgs/commercial/jwellary2.png'],
    blurb: 'Giva store by BrandKettle.',
    segment: 'commercial',
    alt: 'Jewellery Store Interior Design - Giva',
  },
  {
    slug: 'indriya',
    name: 'Indriya',
    location: 'India',
    category: 'Jewellery Showroom',
    area: 'TBD',
    year: '2024',
    image: '/imgs/commercial/indriya-placeholder.jpg',
    gallery: ['/imgs/commercial/indriya-placeholder.jpg'],
    blurb: 'Indriya jewellery showroom project by BrandKettle.',
    segment: 'commercial',
    alt: 'Jewellery Store Interior Design - Indriya',
  },
  {
    slug: 'havana-lounge-bareilly',
    name: 'Havana Lounge',
    location: 'Rooftop, Ramada Hotel, Bareilly',
    category: 'Hospitality',
    area: '8,500 sq ft',
    year: '2022',
    image: '/imgs/commercial/Havana lounge1.jpg',
    gallery: ['/imgs/commercial/Havana lounge1.jpg', '/imgs/commercial/havana lounge2.jpg', '/imgs/commercial/havana lounge 3.jpg', '/imgs/commercial/havana lounge4.jpg', '/imgs/commercial/havna lounge5.jpg'],
    blurb: "A standout rooftop project (Studio AKAAI) on the roof of the Ramada hotel, Bareilly. Highlights BrandKettle's expertise in design thinking, detailing and craftsmanship.",
    segment: 'commercial',
    alt: 'Commercial Fit-Out Company - Havana Lounge Rooftop Bareilly',
  },
  {
    slug: 'pret-a-manger-delhi',
    name: 'Pret A Manger',
    location: 'Select City Walk, Delhi',
    category: 'Hospitality',
    area: '2,200 sq ft',
    year: '2023',
    image: '/imgs/commercial/p080_111.jpg',
    gallery: ['/imgs/commercial/p080_111.jpg'],
    blurb: "The iconic Pret A Manger store brought to life at Select City Walk, Delhi. Showcases BrandKettle's commitment to exceptional design and branding, creating a vibrant, inviting space that brings the renowned brand to the heart of Delhi.",
    segment: 'commercial',
    alt: 'Retail Fit-Out Company - Pret A Manger Select City Walk',
  },
  {
    slug: 'ramada-encore-bareilly',
    name: 'Ramada Encore Hotel',
    location: 'Bareilly',
    category: 'Hospitality',
    area: '25,000 sq ft',
    year: '2023',
    image: '/imgs/commercial/ramda encre hotel1.jpg',
    gallery: [ '/imgs/commercial/ramda encre hotel1.jpg', '/imgs/commercial/ramda encore hotel2.jpg', '/imgs/commercial/ramda encore hotel3.jpg', '/imgs/commercial/p064_079.jpg', '/imgs/commercial/p066_087.jpg'],
    blurb: "BrandKettle's first collaboration with a luxury hotel. Centrally located in the medical hub, under 1 km from Bareilly Jn. train station and 11 km from Bareilly Airport (BEK). A new chapter where brand identity meets functionality.",
    segment: 'commercial',
    alt: 'Commercial Interior Contractors - Ramada Encore Hotel Bareilly',
  },
  {
    slug: 'nanokirti-pvt',
    name: 'Nanokirti Pvt',
    location: 'India',
    category: 'Corporate Office',
    area: '12,000 sq ft',
    year: '2023',
    image: '/imgs/commercial/nanokirti pvt1.jpg',
    gallery: ['/imgs/commercial/nanokirti pvt1.jpg', '/imgs/commercial/nanokirti pvt2.jpg', '/imgs/commercial/nanokirti pvt3.jpg'],
    blurb: 'A modernized corporate workspace tailored to reflect a forward-thinking culture. Designed with open collaborative zones, acoustic-treated meeting rooms, and ergonomic workstations to ensure productivity and well-being.',
    segment: 'commercial',
    alt: 'Office Fit-Out Company - Nanokirti Pvt Corporate Workspace',
  },
  {
    slug: 'and-work-faridabad',
    name: '&Work Co-working Space',
    location: 'Faridabad',
    category: 'Commercial Spaces',
    area: '15,000 sq ft',
    year: '2021',
    image: '/imgs/commercial/work co workspace.jpg',
    gallery: ['/imgs/commercial/work co workspace.jpg', '/imgs/commercial/work co workspace1.jpg', '/imgs/commercial/work co work space2.jpg'],
    blurb: "One of BrandKettle's cherished projects — a fun and creative co-working space delivered in Faridabad.",
    segment: 'commercial',
    alt: 'Corporate Interior Solutions - &Work Co-working Space Faridabad',
  }
];
